// packages/app-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ArticleComponent } from './article/article.component';
import { AuthComponent } from './auth/auth.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AuthComponent, ArticleComponent],
  template: `
    <header>
      <h1>Frontend Archetype — Angular</h1>
      <app-auth />
    </header>
    <main>
      <app-article />
    </main>
  `,
})
export class AppComponent {}

// packages/app-react/src/App.tsx
import { Provider } from 'react-redux';
import { store } from './store/store';
import { AuthBar } from './auth/AuthBar';
import { ArticlePage } from './article/ArticlePage';

export default function App() {
  return (
    <Provider store={store}>
      <header>
        <h1>Frontend Archetype — React</h1>
        <AuthBar />
      </header>
      <main>
        <ArticlePage />
      </main>
    </Provider>
  );
}
