// packages/app-angular/src/app/auth/login-modal.component.ts
import { Component, inject, OnInit, signal, output } from '@angular/core';
import { AuthViewModel, UserViewModel } from '@frontend-archetype/core';
import {
  LOGIN_USE_CASE,
  LOGIN_PRESENTER,
  GET_ALL_USERS_USE_CASE,
  GET_ALL_USERS_PRESENTER,
} from '../di/app.providers';

@Component({
  selector: 'app-login-modal',
  standalone: true,
  templateUrl: './login-modal.component.html',
})
export class LoginModalComponent implements OnInit {
  private readonly loginUseCase = inject(LOGIN_USE_CASE);
  private readonly loginPresenter = inject(LOGIN_PRESENTER);
  private readonly getAllUsersUseCase = inject(GET_ALL_USERS_USE_CASE);
  private readonly getAllUsersPresenter = inject(GET_ALL_USERS_PRESENTER);

  readonly loggedIn = output<AuthViewModel>();
  readonly closed = output<void>();

  readonly users = signal<UserViewModel[]>([]);
  readonly isLoading = signal(false);
  readonly error = signal<string | null>(null);

  async ngOnInit(): Promise<void> {
    const result = await this.getAllUsersUseCase.execute();
    if (result.isOk) {
      this.users.set(this.getAllUsersPresenter.present(result.value));
    }
  }

  async selectUser(userId: string): Promise<void> {
    this.isLoading.set(true);
    this.error.set(null);

    const result = await this.loginUseCase.execute({ userId });

    if (result.isErr) {
      this.error.set(result.error.message);
      this.isLoading.set(false);
      return;
    }

    this.loggedIn.emit(this.loginPresenter.present(result.value));
    this.isLoading.set(false);
  }

  close(): void {
    this.closed.emit();
  }
}

<div class="modal-backdrop" (click)="close()">
  <div class="modal" (click)="$event.stopPropagation()">
    <h2>Choisir un utilisateur</h2>

    @if (error()) {
      <p class="error">{{ error() }}</p>
    }

    <ul class="user-list">
      @for (user of users(); track user.id) {
        <li>
          <button (click)="selectUser(user.id)" [disabled]="isLoading()">
            {{ user.fullName }}
          </button>
        </li>
      }
    </ul>

    <button class="btn-secondary" (click)="close()">Annuler</button>
  </div>
</div>

// packages/app-nextjs/src/components/auth/LoginModal.tsx
'use client';

import { useEffect, useState } from 'react';
import { AuthViewModel, UserViewModel } from '@frontend-archetype/core';

interface LoginModalProps {
  onLoggedIn: (user: AuthViewModel) => void;
  onClose: () => void;
}

export function LoginModal({ onLoggedIn, onClose }: LoginModalProps) {
  const [users, setUsers] = useState<UserViewModel[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/login')
      .then((res) => res.json())
      .then(setUsers);
  }, []);

  const handleSelect = async (userId: string) => {
    setIsLoading(true);
    setError(null);

    const response = await fetch('/api/login', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId }),
    });

    if (!response.ok) {
      const data = await response.json();
      setError(data.error);
      setIsLoading(false);
      return;
    }

    const user: AuthViewModel = await response.json();
    onLoggedIn(user);
    setIsLoading(false);
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>Choisir un utilisateur</h2>

        {error && <p className="error">{error}</p>}

        <ul className="user-list">
          {users.map((user) => (
            <li key={user.id}>
              <button onClick={() => handleSelect(user.id)} disabled={isLoading}>
                {user.fullName}
              </button>
            </li>
          ))}
        </ul>

        <button className="btn-secondary" onClick={onClose}>
          Annuler
        </button>
      </div>
    </div>
  );
}
